#!/usr/bin/env bash
#
# Generated by scripts/gen.py from scripts/issues.json. Do not edit by hand.
#
# Creates the GitHub repo, labels, milestones, and all issues via the gh CLI.
#
# Usage: ./scripts/create_github.sh <owner>/<repo> [--public|--private]
#
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <owner>/<repo> [--public|--private]" >&2
  exit 1
fi

REPO="$1"; shift
VISIBILITY="--private"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --public)  VISIBILITY="--public" ;;
    --private) VISIBILITY="--private" ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
  shift
done

echo "==> Verifying gh authentication"
gh auth status >/dev/null

echo "==> Creating repo $REPO ($VISIBILITY)"
if gh repo view "$REPO" >/dev/null 2>&1; then
  echo "    repo already exists, skipping creation"
else
  gh repo create "$REPO" $VISIBILITY \
    --description 'A tiny web game where you try to out-predict a small char-level language model, one word at a time.' \
    --source=. --remote=origin --push
fi

echo "==> Creating labels"
gh label create 'area:model' --repo "$REPO" --color 1d76db --description 'Char-level GPT definition, tokenizer, training' --force
gh label create 'area:server' --repo "$REPO" --color 0e8a16 --description 'FastAPI app, puzzle generation, rollout, scoring' --force
gh label create 'area:web' --repo "$REPO" --color 5319e7 --description 'Single-page frontend' --force
gh label create 'area:infra' --repo "$REPO" --color b60205 --description 'Project skeleton, tooling, deployment' --force
gh label create 'area:docs' --repo "$REPO" --color c2e0c6 --description 'Documentation and run instructions' --force
gh label create 'enhancement' --repo "$REPO" --color a2eeef --description 'Improves an existing capability' --force

echo "==> Creating milestones"
# gh has no native milestone command; use the REST API. 422 means it already exists.
gh api "repos/$REPO/milestones" --silent -f title='M1: MVP' -f description='The full loop playable end to end on one corpus, using a simple single-token puzzle.' >/dev/null 2>&1 || echo "    milestone M1: MVP exists or skipped"
gh api "repos/$REPO/milestones" --silent -f title='M2: Next-word puzzles' -f description='Upgrade the mechanic to the full next-word greedy rollout with probability-mass scoring.' >/dev/null 2>&1 || echo "    milestone M2: Next-word puzzles exists or skipped"
gh api "repos/$REPO/milestones" --silent -f title='M3: Multiple corpora' -f description='Train and serve several corpora; let the player choose which book to play.' >/dev/null 2>&1 || echo "    milestone M3: Multiple corpora exists or skipped"
gh api "repos/$REPO/milestones" --silent -f title='M4: Polish & deploy' -f description='Session scoring, a real design pass, and deployment + run docs.' >/dev/null 2>&1 || echo "    milestone M4: Polish & deploy exists or skipped"

echo "==> Creating issues"
gh issue create --repo "$REPO" \
  --title 'Project skeleton, dependencies, and /health' \
  --milestone 'M1: MVP' \
  --label 'area:infra' \
  --body-file - <<'WORDGUESS_ISSUE_BODY'
Stand up the repository skeleton so every later issue has a home. Create the Python package layout under model/ and server/, a requirements.txt (or pyproject) pinning torch, fastapi, uvicorn, a minimal FastAPI app exposing GET /health, and a short dev-setup section in the README explaining how to create a venv, install deps, and run the server.

## Acceptance criteria

- [ ] A virtualenv can be created and `pip install -r requirements.txt` succeeds on CPU-only machines.
- [ ] `uvicorn server.app:app` starts without error.
- [ ] `GET /health` returns `{"status": "ok"}` with HTTP 200.
- [ ] README documents the exact setup + run commands.
- [ ] model/, server/, web/, corpora/ exist with package __init__ files where appropriate.

## Out of scope

- No model definition, training, or puzzle logic yet.
- No frontend beyond what already exists in web/.
- No Docker or deployment config (that is M4).
WORDGUESS_ISSUE_BODY

gh issue create --repo "$REPO" \
  --title 'Char-level GPT model definition (nanoGPT-style)' \
  --milestone 'M1: MVP' \
  --label 'area:model' \
  --body-file - <<'WORDGUESS_ISSUE_BODY'
Define a trimmed char-level GPT in the nanoGPT lineage in model/: token + positional embeddings, a few transformer blocks with causal self-attention, LayerNorm, and a linear head. Provide a small config dataclass with defaults (n_layer=4, n_head=4, n_embd=128, block_size=128). Keep it CPU-runnable and readable in one sitting.

## Acceptance criteria

- [ ] A `GPT` module and a `GPTConfig` dataclass exist in model/.
- [ ] A forward pass on a random `(batch, block_size)` int tensor returns logits shaped `(batch, block_size, vocab_size)`.
- [ ] Causal masking is applied so position t never attends to positions > t.
- [ ] Model instantiates and runs a forward pass on CPU with the default config.
- [ ] Code favors clarity: named sub-modules, short docstrings, no premature abstraction.

## Out of scope

- No training loop (separate issue).
- No tokenizer (separate issue).
- No generation/sampling helpers beyond a plain forward pass.
WORDGUESS_ISSUE_BODY

gh issue create --repo "$REPO" \
  --title 'Char-level tokenizer' \
  --milestone 'M1: MVP' \
  --label 'area:model' \
  --body-file - <<'WORDGUESS_ISSUE_BODY'
Implement a minimal char-level tokenizer in model/: build a vocabulary from a corpus's unique characters, with encode(str)->list[int] and decode(list[int])->str, plus save/load of the vocabulary (stoi/itos) so training and serving agree on the mapping.

## Acceptance criteria

- [ ] `encode` then `decode` round-trips any string drawn from the training corpus exactly.
- [ ] Vocabulary can be saved to and loaded from disk (e.g. JSON) alongside a checkpoint.
- [ ] Tokenizer exposes `vocab_size`.
- [ ] Decoding an out-of-range id fails loudly rather than silently corrupting output.

## Out of scope

- No subword/BPE tokenization — char-level only.
- No corpus downloading (a sample corpus is provided by the training issue).
WORDGUESS_ISSUE_BODY

gh issue create --repo "$REPO" \
  --title 'Training script for one corpus' \
  --milestone 'M1: MVP' \
  --label 'area:model' \
  --body-file - <<'WORDGUESS_ISSUE_BODY'
Add a training script in model/ that reads a corpus text file, builds the tokenizer, trains the GPT with a simple loop (AdamW, cross-entropy on next-char prediction, periodic train/val loss logging), and writes a checkpoint (weights + config + vocab) under corpora/<name>/. Include one small public-domain sample corpus (e.g. a Project Gutenberg text) committed as raw text.

## Acceptance criteria

- [ ] `python -m model.train --corpus corpora/<name>/input.txt` trains on CPU in a few minutes and prints decreasing loss.
- [ ] A checkpoint containing weights, GPTConfig, and vocab is written under corpora/<name>/ (weights path is gitignored).
- [ ] The script has sensible CLI defaults and a fixed random seed for reproducibility.
- [ ] A public-domain sample corpus text is committed under corpora/.
- [ ] A short sample of generated text is printed at the end as a sanity check.

## Out of scope

- No multi-corpus orchestration (that is M3).
- No GPU-specific code paths required.
- No hyperparameter search.
WORDGUESS_ISSUE_BODY

gh issue create --repo "$REPO" \
  --title 'Inference service: load model + single-token next-char prediction' \
  --milestone 'M1: MVP' \
  --label 'area:server' --label 'area:model' \
  --body-file - <<'WORDGUESS_ISSUE_BODY'
Add a prediction layer the server can call: load a checkpoint (weights + config + vocab) into memory once at startup, and expose a function that, given a prompt string, returns the next-char probability distribution (softmax over the vocab) for the final position. This is the single-token primitive the MVP puzzle builds on.

## Acceptance criteria

- [ ] A loader reconstructs the model from a checkpoint and puts it in eval mode on CPU.
- [ ] `predict_next(prompt) -> list[(char, prob)]` returns a valid probability distribution (sums to ~1).
- [ ] Prompt longer than block_size is truncated to the last block_size chars.
- [ ] The model is loaded once and reused across calls (no reload per request).
- [ ] A tiny unit test or script demonstrates top-K next chars for a sample prompt.

## Out of scope

- No multi-token / next-word rollout yet (that is M2).
- No HTTP endpoints in this issue — pure prediction layer.
- No corpus selection (single model).
WORDGUESS_ISSUE_BODY

gh issue create --repo "$REPO" \
  --title 'Puzzle generation + /puzzle and /guess (single-token)' \
  --milestone 'M1: MVP' \
  --label 'area:server' \
  --body-file - <<'WORDGUESS_ISSUE_BODY'
Build the single-token puzzle loop and expose it over HTTP. Generation: take a random slice of the corpus as the prompt, compute the next-char distribution, set correct = argmax char and distractors = ranks 2..K, shuffle the choices, and cache the answer server-side keyed by puzzle_id. Endpoints: POST /puzzle -> {puzzle_id, prompt, choices[]} and POST /guess -> {puzzle_id, choice_idx} -> {correct_idx, probs[], your_prob, score?}.

## Acceptance criteria

- [ ] POST /puzzle returns a puzzle_id, a prompt, and shuffled choices; the correct index is NOT inferable from the response.
- [ ] The correct answer and per-choice probabilities are stored in a short-lived in-memory cache keyed by puzzle_id.
- [ ] POST /guess returns correct_idx, the probability spread, and the probability the player's choice carried.
- [ ] Guessing an unknown or expired puzzle_id returns a clean 404-style error.
- [ ] A basic score is derived from the probability mass of the guess.

## Out of scope

- No next-word rollout (M2 replaces the single-token candidates).
- No persistent storage — in-memory cache only.
- No multi-corpus routing (M3).
WORDGUESS_ISSUE_BODY

gh issue create --repo "$REPO" \
  --title 'Minimal playable frontend' \
  --milestone 'M1: MVP' \
  --label 'area:web' \
  --body-file - <<'WORDGUESS_ISSUE_BODY'
A single HTML page with vanilla JS (no build step) that calls /puzzle, renders the prompt with a blank and one button per candidate, submits the pick to /guess, and shows the reveal: the correct word highlighted plus the probability spread and the player's score. Keep it clean but plain — design polish is deferred to M4.

## Acceptance criteria

- [ ] Loading the page fetches and displays a puzzle with clickable candidate buttons.
- [ ] Clicking a candidate calls /guess and reveals the correct answer and probability spread.
- [ ] A 'next puzzle' action fetches a fresh puzzle without a full reload.
- [ ] Works when served alongside the FastAPI app; no bundler or npm install required.
- [ ] The correct answer is never present in the page before the guess is submitted.

## Out of scope

- No design system, animations, or responsive polish (that is M4).
- No corpus picker (M3).
- No session/streak tracking (M4).
WORDGUESS_ISSUE_BODY

gh issue create --repo "$REPO" \
  --title 'Next-word greedy rollout in the inference layer' \
  --milestone 'M2: Next-word puzzles' \
  --label 'area:model' --label 'area:server' \
  --body-file - <<'WORDGUESS_ISSUE_BODY'
Add the greedy rollout primitive. Given a prompt, take the top-K first next-chars, and for each roll forward greedily char-by-char until a word boundary (whitespace/punctuation), multiplying probabilities along the way. Return one candidate word per branch with its cumulative probability.

## Acceptance criteria

- [ ] `rollout_words(prompt, k) -> list[(word, cumulative_prob)]` returns K candidate words.
- [ ] Each rollout stops at the first word boundary after the branch point.
- [ ] Cumulative probability is the product of per-step probabilities along the greedy path.
- [ ] Candidates are de-duplicated if two branches produce the same word (keep the higher probability).
- [ ] A script prints the candidate words and probabilities for a sample prompt.

## Out of scope

- No beam search — greedy per-branch only.
- No endpoint changes in this issue (next issue wires it in).
- No scoring changes yet.
WORDGUESS_ISSUE_BODY

gh issue create --repo "$REPO" \
  --title 'Switch /puzzle and /guess to next-word candidates' \
  --milestone 'M2: Next-word puzzles' \
  --label 'area:server' \
  --body-file - <<'WORDGUESS_ISSUE_BODY'
Wire the rollout into puzzle generation. Replace single-token candidates with the next-word candidates from rollout_words: correct = highest cumulative probability, distractors = the rest. Keep the same request/response shapes so the frontend keeps working.

## Acceptance criteria

- [ ] POST /puzzle returns whole-word choices produced by the rollout.
- [ ] The correct word is the highest-cumulative-probability candidate and remains un-leaked.
- [ ] POST /guess returns the per-word probability spread.
- [ ] The existing frontend works unchanged against the new candidates.
- [ ] Single-token generation is fully replaced (no dead code left behind).

## Out of scope

- No frontend redesign.
- No new scoring formula in this issue (next issue handles scoring).
WORDGUESS_ISSUE_BODY

gh issue create --repo "$REPO" \
  --title 'Probability-mass scoring' \
  --milestone 'M2: Next-word puzzles' \
  --label 'area:server' \
  --body-file - <<'WORDGUESS_ISSUE_BODY'
Define the score from how much probability mass the player's chosen word carried, normalized across the candidate set, so the model's 2nd choice hurts less than its 5th. Return the score from /guess and document the formula.

## Acceptance criteria

- [ ] Score is a function of the chosen word's cumulative probability relative to the candidate set.
- [ ] Picking the correct (top) word yields the maximum score; a near-miss scores higher than a wild miss.
- [ ] The scoring formula is documented in code and README.
- [ ] /guess returns the numeric score alongside your_prob and the probability spread.

## Out of scope

- No cross-session aggregation or streaks (that is M4).
- No leaderboards or persistence.
WORDGUESS_ISSUE_BODY

gh issue create --repo "$REPO" \
  --title 'Multi-corpus training + checkpoint registry' \
  --milestone 'M3: Multiple corpora' \
  --label 'area:model' --label 'area:server' \
  --body-file - <<'WORDGUESS_ISSUE_BODY'
Support several corpora. Train a separate model per corpus under corpora/<name>/, and add a registry the server reads at startup to discover available corpora and load each checkpoint into memory. Add at least one more public-domain sample corpus.

## Acceptance criteria

- [ ] Training can target any corpus directory and writes an isolated checkpoint per corpus.
- [ ] A registry lists available corpora with a short human-readable description each.
- [ ] The server loads all registered corpus models into memory at startup.
- [ ] At least two public-domain corpora are available.
- [ ] Missing or corrupt checkpoints are reported clearly at startup rather than crashing silently.

## Out of scope

- No lazy/on-demand model loading required.
- No training scheduler or automation.
- No UI changes in this issue (next issue handles selection).
WORDGUESS_ISSUE_BODY

gh issue create --repo "$REPO" \
  --title 'Corpus selection in API and UI + /corpora' \
  --milestone 'M3: Multiple corpora' \
  --label 'area:server' --label 'area:web' \
  --body-file - <<'WORDGUESS_ISSUE_BODY'
Expose GET /corpora returning available corpus names + descriptions, accept an optional corpus field on POST /puzzle to route to that model, and add a corpus picker to the frontend that lists corpora and starts puzzles from the chosen one.

## Acceptance criteria

- [ ] GET /corpora returns the registered corpus names and descriptions.
- [ ] POST /puzzle honors an optional `corpus` field and routes to the matching model.
- [ ] Omitting `corpus` falls back to a sensible default corpus.
- [ ] The frontend shows a picker and starts puzzles from the selected corpus.
- [ ] Requesting an unknown corpus returns a clean error.

## Out of scope

- No per-corpus difficulty tuning.
- No design polish (that is M4).
WORDGUESS_ISSUE_BODY

gh issue create --repo "$REPO" \
  --title 'Session scoring and streaks' \
  --milestone 'M4: Polish & deploy' \
  --label 'area:web' --label 'area:server' \
  --body-file - <<'WORDGUESS_ISSUE_BODY'
Track a running score and streak within a play session so the game feels like a game. Accumulate across puzzles (client-side state is fine), show total score, current streak, and best streak, and reset cleanly on demand.

## Acceptance criteria

- [ ] The UI shows running total score and current streak across consecutive puzzles.
- [ ] Best streak is tracked within the session.
- [ ] A reset control clears session stats.
- [ ] Scoring is consistent with the M2 probability-mass score.

## Out of scope

- No accounts, login, or server-side persistence.
- No global leaderboard.
WORDGUESS_ISSUE_BODY

gh issue create --repo "$REPO" \
  --title 'Frontend design pass' \
  --milestone 'M4: Polish & deploy' \
  --label 'area:web' \
  --body-file - <<'WORDGUESS_ISSUE_BODY'
A real visual pass on the single page: readable typography, clear layout for prompt/candidates/reveal, a legible probability-spread visualization, responsive behavior on small screens, and gentle feedback on guess. Keep it dependency-light (no heavy framework).

## Acceptance criteria

- [ ] The page has a coherent visual design: type scale, spacing, and color used deliberately.
- [ ] The probability spread is shown as a simple, legible chart (e.g. bars).
- [ ] Layout is usable on a phone-width screen.
- [ ] Guess feedback (correct/near/far) is visually clear.
- [ ] Still no build step required, or a minimal documented one.

## Out of scope

- No SPA framework migration unless justified and documented.
- No change to the game mechanic or API.
WORDGUESS_ISSUE_BODY

gh issue create --repo "$REPO" \
  --title 'Deployment and run docs' \
  --milestone 'M4: Polish & deploy' \
  --label 'area:infra' --label 'area:docs' \
  --body-file - <<'WORDGUESS_ISSUE_BODY'
Make the game runnable by someone else. Provide a reproducible way to serve the app (documented uvicorn command and/or a simple Dockerfile), document how to train models and where checkpoints live, and note resource expectations (CPU-only, memory footprint).

## Acceptance criteria

- [ ] A documented single command (or Dockerfile) serves the app locally.
- [ ] README explains end to end: install, train a corpus, run the server, play.
- [ ] Checkpoint location and the fact that weights are gitignored are documented.
- [ ] Resource expectations (CPU-only, approximate memory) are stated.
- [ ] A fresh clone can reach a playable game by following the docs.

## Out of scope

- No managed cloud provisioning or CI/CD pipeline required.
- No autoscaling or multi-instance concerns.
WORDGUESS_ISSUE_BODY

echo "==> Done. Created labels, milestones, and issues for $REPO"
gh repo view "$REPO" --web >/dev/null 2>&1 || true
