#!/usr/bin/env python3
"""Regenerate BACKLOG.md and scripts/create_github.sh from scripts/issues.json.

issues.json is the single source of truth for the backlog. Edit it, then run:

    python scripts/gen.py

This keeps the human-readable backlog and the GitHub-creation script in sync.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ISSUES_JSON = ROOT / "scripts" / "issues.json"
BACKLOG_MD = ROOT / "BACKLOG.md"
CREATE_SH = ROOT / "scripts" / "create_github.sh"


def load() -> dict:
    return json.loads(ISSUES_JSON.read_text())


def issue_body(issue: dict) -> str:
    """Markdown body for a single issue: scope, acceptance checkboxes, out-of-scope."""
    lines = [issue["scope"], "", "## Acceptance criteria", ""]
    lines += [f"- [ ] {a}" for a in issue["acceptance"]]
    lines += ["", "## Out of scope", ""]
    lines += [f"- {o}" for o in issue["out_of_scope"]]
    return "\n".join(lines).strip() + "\n"


def write_backlog(data: dict) -> None:
    out = ["# wordguess — backlog", ""]
    out += [
        "_Generated from [`scripts/issues.json`](scripts/issues.json) by "
        "`scripts/gen.py`. Do not edit by hand._",
        "",
    ]
    for milestone in data["milestones"]:
        issues = [i for i in data["issues"] if i["milestone"] == milestone["name"]]
        out.append(f"## {milestone['name']}")
        out.append("")
        out.append(f"_{milestone['description']}_")
        out.append("")
        for issue in issues:
            labels = ", ".join(f"`{l}`" for l in issue["labels"])
            out.append(f"### {issue['title']}")
            out.append("")
            out.append(f"**Labels:** {labels}")
            out.append("")
            out.append(issue["scope"])
            out.append("")
            out.append("**Acceptance criteria**")
            out.append("")
            out += [f"- [ ] {a}" for a in issue["acceptance"]]
            out.append("")
            out.append("**Out of scope**")
            out.append("")
            out += [f"- {o}" for o in issue["out_of_scope"]]
            out.append("")
    BACKLOG_MD.write_text("\n".join(out).rstrip() + "\n")


def sh_quote(s: str) -> str:
    """Single-quote a string safely for bash."""
    return "'" + s.replace("'", "'\\''") + "'"


def write_create_script(data: dict) -> None:
    L = []
    a = L.append
    a("#!/usr/bin/env bash")
    a("#")
    a("# Generated by scripts/gen.py from scripts/issues.json. Do not edit by hand.")
    a("#")
    a("# Creates the GitHub repo, labels, milestones, and all issues via the gh CLI.")
    a("#")
    a("# Usage: ./scripts/create_github.sh <owner>/<repo> [--public|--private]")
    a("#")
    a("set -euo pipefail")
    a("")
    a('if [[ $# -lt 1 ]]; then')
    a('  echo "Usage: $0 <owner>/<repo> [--public|--private]" >&2')
    a("  exit 1")
    a("fi")
    a("")
    a('REPO="$1"; shift')
    a('VISIBILITY="--private"')
    a('while [[ $# -gt 0 ]]; do')
    a('  case "$1" in')
    a('    --public)  VISIBILITY="--public" ;;')
    a('    --private) VISIBILITY="--private" ;;')
    a('    *) echo "Unknown arg: $1" >&2; exit 1 ;;')
    a("  esac")
    a("  shift")
    a("done")
    a("")
    a('echo "==> Verifying gh authentication"')
    a("gh auth status >/dev/null")
    a("")
    a('echo "==> Creating repo $REPO ($VISIBILITY)"')
    a("if gh repo view \"$REPO\" >/dev/null 2>&1; then")
    a('  echo "    repo already exists, skipping creation"')
    a("else")
    a("  gh repo create \"$REPO\" $VISIBILITY \\")
    a(f"    --description {sh_quote(data['repo_description'])} \\")
    a('    --source=. --remote=origin --push')
    a("fi")
    a("")
    a('echo "==> Creating labels"')
    for label in data["labels"]:
        a(
            "gh label create {name} --repo \"$REPO\" --color {color} "
            "--description {desc} --force".format(
                name=sh_quote(label["name"]),
                color=label["color"],
                desc=sh_quote(label["description"]),
            )
        )
    a("")
    a('echo "==> Creating milestones"')
    a("# gh has no native milestone command; use the REST API. 422 means it already exists.")
    for m in data["milestones"]:
        a(
            "gh api \"repos/$REPO/milestones\" --silent "
            "-f title={title} -f description={desc} "
            ">/dev/null 2>&1 || echo \"    milestone {title_plain} exists or skipped\"".format(
                title=sh_quote(m["name"]),
                desc=sh_quote(m["description"]),
                title_plain=m["name"],
            )
        )
    a("")
    a('echo "==> Creating issues"')
    for issue in data["issues"]:
        labels_flags = " ".join(
            f"--label {sh_quote(l)}" for l in issue["labels"]
        )
        a("gh issue create --repo \"$REPO\" \\")
        a(f"  --title {sh_quote(issue['title'])} \\")
        a(f"  --milestone {sh_quote(issue['milestone'])} \\")
        a(f"  {labels_flags} \\")
        a("  --body-file - <<'WORDGUESS_ISSUE_BODY'")
        a(issue_body(issue).rstrip("\n"))
        a("WORDGUESS_ISSUE_BODY")
        a("")
    a('echo "==> Done. Created labels, milestones, and issues for $REPO"')
    a('gh repo view "$REPO" --web >/dev/null 2>&1 || true')
    a("")
    CREATE_SH.write_text("\n".join(L))
    CREATE_SH.chmod(0o755)


def main() -> None:
    data = load()
    write_backlog(data)
    write_create_script(data)
    n = len(data["issues"])
    print(f"Wrote {BACKLOG_MD.relative_to(ROOT)} and {CREATE_SH.relative_to(ROOT)}")
    print(
        f"  {len(data['labels'])} labels, {len(data['milestones'])} milestones, "
        f"{n} issues"
    )


if __name__ == "__main__":
    main()
